"""empty message

Revision ID: 05e72ac4aedb
Revises: 2f37e0814ea2
Create Date: 2022-07-03 17:47:26.189288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05e72ac4aedb"
down_revision = "2f37e0814ea2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
