"""empty message

Revision ID: 2f37e0814ea2
Revises: 24dc6223b817
Create Date: 2022-07-03 17:45:20.370343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f37e0814ea2"
down_revision = "24dc6223b817"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
